name: Auto-Clean

on:
  workflow_call:

    #自动清理：每天早上2点
  schedule:
    - cron: 0 18 * * *
  #手动清理
  workflow_dispatch:

permissions: write-all

jobs:
  Cleaning:
    runs-on: ubuntu-22.04

    steps:
    - name: Delete Old Workflows
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        retain_days: 2
        keep_minimum_runs: 0
        delete_releases: true
        releases_keep_latest: 0
        delete_tags: true
        delete_workflows: true
        workflows_keep_day: 0

    - name: Delete Old Releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 8
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
